### ISSUE TITLE
[Critique-Issue] Function Fails to Properly Close DB Connection

### ISSUE THREAD

**Issue by TCF-30** [joverkamp/SPDXHub#103]
The function "getLicenseVerifier()" in the file "SPDXHub/src/function/spdx_doc.php" fails to properly close it's open database connection before returning the results of the executed query.

Like the other function definitions in the same file - instead of immediately returning the query results consider saving the results to a variable, closing the mysql DB connection, and then returning the results variable.

**Comment by joverkamp** [comment]
That was one of the last database calls I made, simply an oversight - thanks for bringing this to my attention.
