### ISSUE TITLE
[Critique-Issue] Operating System Support Question

### ISSUE THREAD

**Issue by ryanbeaz** [joverkamp/SPDXHub#106]
Can the SPDXHub (Dashboard) be installed on any operating system besides Ubuntu?  I don't see any specific reason why it couldn't be installed on operating systems such as Debian.  

Please let me know if my assumption is invalid and why.  Otherwise please update the [README.md](https://github.com/joverkamp/SPDXHub/blob/master/README.md) to include this information.

**Comment by joverkamp** [comment]
Technically, the Dash runs on practically any OS (Windows, Mac, Ubuntu), but with the option to scan with fossology I was only able to test with Ubuntu - which is depicted on the README. Should run on most unix systems. So I'll discuss this with my team and make changes to the README accordingly! Thanks!

**Comment by nchickinelli** [comment]
Section changed to: "Tested Environment".
