### ISSUE TITLE
[Critique-Issue] Minimum Memory Requirement

### ISSUE THREAD

**Issue by ryanbeaz** [joverkamp/SPDXHub#107]
Please remove the memory requirement included in the [README.md](https://github.com/joverkamp/SPDXHub/blob/master/README.md) in order to install SPDXHub (Dashboard).  

To me, It is irrelevant and unknown how much memory is required.

**Comment by joverkamp** [comment]
Indeed. This has been removed and replaced to indicate it was the environment we tested in.
