### ISSUE TITLE
[Critique-Issue] Installation Command Issue #1

### ISSUE THREAD

**Issue by ryanbeaz** [joverkamp/SPDXHub#108]
After running the linked install.sh file, I proceeded to run the following command as outlined in the INSTALL.md file:

```
sudo cp /var/www/SPDXHub/doc/SPDXHub.conf /etc/apache2/sites- available/SPDXHub.conf
```

Running this command produced the following error on my local machine:

![screen shot 2015-04-17 at 10 02 46 pm](https://cloud.githubusercontent.com/assets/10524468/7213717/fa9df0da-e54d-11e4-96d6-509dd9f6d602.png)

I think this is an easy fix, just wanted to point it out.

**Comment by joverkamp** [comment]
Looks like there was a line-break I missed. Note: As it mentions in that .md file - that directory may differ from machine to machine, but the mistype has been corrected.
