### ISSUE TITLE
[Critique-Issue] Installation Command Issue #2

### ISSUE THREAD

**Issue by ryanbeaz** [joverkamp/SPDXHub#109]
After I failed to run the command outlined in issue #108, I tried to run the following command which also failed:

```
sudo a2ensite SPDXHub.conf
```

Running this command produced the following error on my local machine:

![screen shot 2015-04-17 at 10 08 16 pm](https://cloud.githubusercontent.com/assets/10524468/7213729/728f9bac-e54e-11e4-8055-80e5031bf884.png)

I think this is an easy fix, just wanted to point it out.

**Comment by joverkamp** [comment]
This was procured due to the fact that the SPDXHub.conf file was never added to the site-available folder. Having corrected that mis-type, this issue would be resolved as well.
