### ISSUE TITLE
[Critique-Issue] Installation Guide Change

### ISSUE THREAD

**Issue by ryanbeaz** [joverkamp/SPDXHub#110]
Hello!  After running through all of the install instructions I came across the following text located in the INSTALL.md file:

```
NOTE you will be required to configure the Data_Source.php file located at
"/var/www/SPDXHub/src/function/Data_Source.php" with your mySQL credentials and
your path to DoSPDX.py
```

Can you please provide a specific set of instructions of how users can go about making this change?  That would be helpful for other users installing your system.

**Comment by joverkamp** [comment]
I feel the information we provided in that note should be sufficient. It provides the default path for the file that needs to be edited and the information that needs to be revised. The most I could add would be a note informing that this file is making the database connection.
