### ISSUE TITLE
[DOC] Make sure Milestones are consistent across wiki and readme

### ISSUE THREAD

**Issue by nchickinelli** [joverkamp/SPDXHub#51]
Check the wiki against readme. Moving forward the wiki will act as a working document and the readme will change based on consensus in regards to the wiki milestones.

**Comment by nchickinelli** [comment]
Team, 

Lets do this today during our class meeting.

**Comment by joverkamp** [comment]
This is now accurate with all necessary changes made to the existing milestones.
