### ISSUE TITLE
[TECH] Index.php – Counting successful SPDX retrievals from DB

### ISSUE THREAD

**Issue by nchickinelli** [joverkamp/SPDXHub#88]
Currently, using HTML5 standard table structure, index page shows "1 out of 1 entries" when there are none. 

Khangal, we should touch base on this during tomorrow's meeting.

**Comment by hangal2001** [comment]
I will be there on today's meeting. I send you guys a msg though.

**Comment by joverkamp** [comment]
This has not always been the case. But a change was made recently where the header is now considered a retrieval for the table. You can test this by simply clicking the white space to the left of date selection. The header for the table is sorted in a very distorted manner. Will need to be corrected.

**Comment by nchickinelli** [comment]
fixed ya'll
